airline/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('flights/', include('flights.urls')),
    path('users/', include('users.urls'))
]

flights/urls.py
from django.urls import path
from . import views

app_name = 'flights'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:flight_id>', views.flight, name='flight'),
    path('<int:flight_id>/book', views.book, name='book')
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout')
]

flights/models.py
from django.db import models

# Create your models here.
class Airport(models.Model):
    code = models.CharField(max_length=3)
    city = models.CharField(max_length=64)
    
    def __str__(self):
        return f'{self.city} ({self.code})'
    

class Flights(models.Model):
    origin = models.ForeignKey(Airport, on_delete=models.CASCADE, related_name='departures')
    destination = models.ForeignKey(Airport, on_delete=models.CASCADE, related_name='arrivals')
    duration = models.IntegerField()
    
    def __str__(self):
        return f'{self.id}: {self.origin} to {self.destination}'
    
class Passenger(models.Model):
    f_name = models.CharField(max_length=32)
    l_name = models.CharField(max_length=32)
    flights = models.ManyToManyField(Flights, blank=True, related_name='passenger')

    def __str__(self):
        return f'{self.f_name} {self.l_name}'

users/models.py
from django.db import models

# Create your models here.

flights/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from .models import Flights, Passenger




# Create your views here.
def index(request):
    return render(request, 'flights/index.html', {
       'flights': Flights.objects.all() 
    })

def flight(request, flight_id):
   try:
      flight = Flights.objects.get(pk=flight_id)
   except:
      return HttpResponse('not found')
   
   return render(request, 'flights/flight.html', {
      'flight': flight, 
      'passengers': flight.passenger.all(),
      'notPassenger': Passenger.objects.exclude(flights = flight).all()
   })

def book(request, flight_id):
   if request.method == 'POST':
      flight = Flights.objects.get(pk=flight_id)
      passenger = Passenger.objects.get(pk = int(request.POST['passenger']))
      passenger.flights.add(flight)
      return HttpResponseRedirect(reverse('flights:flight', args=(flight_id,)))

users/views.py
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

# Create your views here.
def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('users:login'))
    return render(request, 'user/users.html')

def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('users:index'))
        else:
            return render(request, 'user/login.html', {
                'message': 'Invalid credentials'
            })
        
    return render(request, 'user/login.html')

def logout_view(request):
    logout(request)
    return render(request, 'user/login.html', {
        'message': 'Logged out'
    })

flights/templates/flights/flight.html
{% extends "flights/layout.html" %}

{% block title %}  
    Flight
{% endblock title %}

{% block body %}
    <h1>Flight {{flight.id}} </h1>
    <ul>
        <li>Origin: {{ flight.origin }} </li>
        <li>Destination: {{ flight.destination }} </li>
        <li>Duration: {{ flight.duration }} </li>
    </ul>

    <h2>Passengers</h2>
    <ul>
        {% for passenger in passengers %}
            <li> {{ passenger}} </li>
            {% empty %}
                <li>No passenger</li>
        {% endfor %}
    </ul>

    <a href="{% url 'flights:index' %}"> Home </a>

    <h2>Add passenger</h2>
    <form action="{% url 'flights:book' flight.id %}" method = 'POST'>
        {% csrf_token %}
        <select name="passenger">
            {% for passenger in notPassenger %}
                <option value="{{ passenger.id }}">{{ passenger }}</option>
            {% endfor %}
        </select>
        <input type="submit">
    </form>

    {% endblock body %}

flights/templates/flights/index.html
{% extends "flights/layout.html" %}

{% block title %}  
    Flights
{% endblock title %}

{% block body %}
    <h1>Flights</h1>
    <ul>
        {% for flight in flights %}
            <li>
                <a href="{% url 'flights:flight' flight.id %}"> Flight {{ flight.id }}: {{ flight.origin }} to {{ flight.destination}} </a>
            </li>
        {% endfor %}
    </ul>
{% endblock body %}

flights/templates/flights/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %} 
        {% endblock title %} 
    </title>
</head>
<body>
    {% block body %}
    {% endblock body %}
</body>
</html>

users/templates/user/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
        {% endblock title %} 
    </title>
</head>
<body>
    {% block body %}
    {% endblock body %}
</body>
</html>

users/templates/user/login.html
{% extends "user/layout.html" %}

{% block title %}
    login
{% endblock title %}


{% block body %}
    {% if message %}
        <div> {{ message }} </div>
    {% endif %}
<p></p> 
    <form action="{% url 'users:login' %}" method='POST'>
        {% csrf_token %}
        <input type="text" name='username' placeholder='Username'>
        <input type="password" name='password' placeholder='Password'>
        <input type="submit" value='Login'>
    </form>
{% endblock body %}

users/templates/user/users.html
{% extends "user/layout.html" %}

{% block title %}
    {{ request.user}}
{% endblock title %}

{% block body %}
    <h1>Hello, {{ request.user.first_name }} </h1>
    <ul>
        <li>Username: {{ request.user.username }} </li>
        <li>Email: {% if request.user.email %} {{ request.user.email }} {% else %} Not Found {% endif %}</li>
    </ul>

    <a href="{% url "users:logout" %}">Log out</a>
{% endblock body %}